config/routes.rb
Rails.application.routes.draw do

  
  root to: "public/homes#top"
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    get 'homes/about'
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
  end
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
   namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    
    def address_display
        '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    has_one_attached :image
    belongs_to :customer
    belongs_to :item
    
    validates :amount, presence: true
    
    def sum_of_price
        item.with_tax_price * amount
    end
    
    def subtotal
        item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ordes, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, presence:true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana,presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_one_attached :image
    has_many :items, dependent: :destroy
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    has_many :order_details, dependent: :destroy
    has_many :cart_items, dependent: :destroy
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: {credit_card: 0, transfer: 1}
    enum status: {waiting: 0, confirm: 1, production: 2, preparing: 3, shipped: 4}
    has_one_attached :image
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: {impossible: 0, waiting: 1, production: 2, complete: 3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number,:is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status, :maiking_status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate!, except: [:top]

    def authenticate!
      if admin_signed_in?
        authenticate_admin!
      else
        authenticate_customer!
      end
    end
    
    def after_sign_in_path_for(resource)
        if customer_signed_in?
             customer_path(resource)
        else admin_sign_in?
          admin_root_path
        end
    end
    
    def after_sign_out_path_for(resource)
            root_path(resource)
    end
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
    
    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2 class="head-line title_h2 text-center">
      <%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集
    </h2>

   <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
   <div class="form-group">
     <label for="last_name">姓</label>
　　　<%= f.text_field :last_name, class: "form-control last_name" %>
　 </div>
　 <div class="form-grouo">
　   <label for="first_name">名</label>
　   <%= f.text_field :first_name, class: "form-control first_name" %>
　 </div>
　 <div class="form-group">
　   <label for="last_name_kana">姓カナ</label>
　   <%= f.text_field :last_name_kana, class: "form-control last_name_kana" %>
　 </div>
　 <div class="form-group">
　   <label for="first_name_kana">名カナ</label>
　   <%= f.text_field :first_name_kana, class: "form-control first_name_kana" %>
　 </div>
　 <div class="form-group">
　   <label for="email">メールアドレス</label>
　   <%= f.text_field :email, class: "form-control email" %>
　 </div>
　 <div class="form-group">
　   <label for="postal_code">郵便番号</label>
　   <%= f.text_field :postal_code, class: "form-control postal_code" %>
　 </div>
　 <div class="form-group">
　   <label for="telephone_number">電話番号</label>
　   <%= f.text_field :telephone_number, class: "form-control telephone_number" %>
　 </div>
　 <div class="form-group">
　   <label for="is_deleted">会員ステータス</label>
　   <%= f.radio_button :is_deleted, true %>
     <%= f.label :is_deleted, "退会済み", {value: :true, style: "display: inline-block;"} %>
     <%= f.radio_button :is_deleted, false %>
     <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
　 </div>
　 <div class="form-group">
　   <%= f.submit '更新', class: "btn btn-success" %>
　 </div>
   <% end %>
   <div>
     <%= link_to "戻る", admin_customer_path, class: "glyphicon glyphicon-home btn btn-info" %>
   </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<h1 class="head-line title_h1 text-center">会員一覧</h1>
<div class="row">
  <div class="col-md-8 offset-md-1">
    <table class="table table-hover table-borderd table-condensed">
      <thead>
        <tr class="info">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
        </tr>
      </thead>
      <tobody>
        <% @customers.each do |customer| %>
        <tr>
          <td>
            <%= customer.id %>
          </td>
          <td>
            <%= link_to admin_customer_path(customer) do %>
            <%= customer.last_name %><%= customer.first_name %>
            <% end %>
          </td>
          <td>
            <%= customer.email %>
          </td>
          <td>
            <% if customer.is_deleted == true %>
              <p><i class="fas fa-bullseye red"></i>退会済み</p>
            <% else %>
              <p><i class="fas fa-bullseye red"></i>有効</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h1 class="head-line title_h1 text-center">
  <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
</h1>
<div class="row">
  <div class="col-md-8 offset-md-1">
    <table class="table">
      <tbody>
        <tr>
          <td>
            <p>顧客ID</p>
            <%= @customer.id %>
            <% if @customer.is_deleted == true %>
              <p>退会済み</p>
            <% else %>
              <p>有効</p>
            <% end %>
          </td>
          <td>
            <p>姓</p>
            <%= @customer.last_name %>
          </td>
          <td>
            <p>名</p>
            <%= @customer.first_name %>
          </td>
          <td>
            <p>姓カナ</p>
            <%= @customer.last_name_kana %>
          </td>
          <td>
            <p>名カナ</p>
            <%= @customer.first_name_kana %>
          </td>
          <td>
            <p>メールアドレス</p>
            <%= @customer.email %>
          </td>
          <td>
            <p>郵便番号</p>
            <%= @customer.postal_code %>
          </td>
          <td>
            <p>住所</p>
            <%= @customer.address %>
          </td>
          <td>
            <p>電話番号</p>
            <%= @customer.telephone_number %>
          </td>
        </tr>
      </tbody>
    </table>
    <div>
      <%= link_to "戻る", admin_customers_path(@customer), class: "glyphicon glyphicon-home btn btn-info" %>
    </div>
  </div>
</div>