config/routes.rb
Rails.application.routes.draw do

  
  root to: "public/homes#top"
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    get 'homes/about'
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
  end
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
   namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    
    def address_display
        '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    has_one_attached :image
    belongs_to :customer
    belongs_to :item
    
    validates :amount, presence: true
    
    def sum_of_price
        item.with_tax_price * amount
    end
    
    def subtotal
        item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ordes, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, presence:true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana,presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_one_attached :image
    has_many :items, dependent: :destroy
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    has_many :order_details, dependent: :destroy
    has_many :cart_items, dependent: :destroy
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: {credit_card: 0, transfer: 1}
    enum status: {waiting: 0, confirm: 1, production: 2, preparing: 3, shipped: 4}
    has_one_attached :image
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: {impossible: 0, waiting: 1, production: 2, complete: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status, :maiking_status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :authenticate_admin!
  
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate!, except: [:top]

    def authenticate!
      if admin_signed_in?
        authenticate_admin!
      else
        authenticate_customer!
      end
    end
    
    def after_sign_in_path_for(resource)
        if customer_signed_in?
             customer_path(resource)
        else admin_sign_in?
          admin_root_path
        end
    end
    
    def after_sign_out_path_for(resource)
            root_path(resource)
    end
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
    
    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h1 class="head-line title_h1 text-center">ジャンル編集</h1>
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
    <div class="form-group">
      <label for="name">ジャンル名</label>
      <%= f.text_field :name, class: "form-control name" %>
    </div>
    <div class="form-group">
      <%= f.submit '変更を保存', class: "btn btn-success" %>
    </div>
    <% end %>
    <div>
      <%= link_to "戻る", admin_genres_path, class: "glyphicon glyphicon-home btn btn-info" %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-3">ジャンル追加</h2>
　　　<%= form_with model: @genre, url: admin_genres_path do |f| %>
　　　<div class="form-group">
　　　  <label for="name">ジャンル名</label>
　　　  <%= f.text_field :name, class: "form-control name" %>
　　　</div>
　　　<div class="form-group">
　　　  <%= f.submit '追加', class: "btn btn-success" %>
　　　</div>
　　　<% end %>
　　</div>
　　<div class="col-md-8 offset-md-1">
　　  <h2>ジャンル一覧</h2>
　　  <table class="table">
　　    <thead>
　　      <tr>
　　        <th>ジャンル名</th>
　　        <th></th>
　　      </tr>
　　    </thead>
　　    <tbody>
　　      <% @genres.each do |genre| %>
　　      <tr>
　　        <td><%= genre.name %></td>
　　        <td class="genre-td">
　　          <%= link_to "編集する", edit_admin_genre_path(genre), class: "glyphicon glyphicon-pencil btn btn-success" %>
　　        </td>
　　      </tr>
　　      <% end %>
　　    </tbody>
　　  </table>
　　</div>
　</div>
</div>

app/views/admin/items/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-o mx-auto">
    <h1>商品編集</h1>
    <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
    <div class="form-group">
      <label for="name">商品名</label>
      <%= f.text_field :name, class: "form-control name" %>
    </div>
    <div class="form-group">
      <label for="image">画像</label>
      <%= f.file_field :image, class: "form-control-image image" %>
    </div>
    <div class="form-group">
      <label for="introduction">商品説明</label>
      <%= f.text_area :introduction, class: "form-control introduction" %>
    </div>
    <div class="form-group">
      <label for="genre">ジャンル</label>
      <%= f.collection_select(:genre_id, @genres, :id, :name) %>
    </div>
    <div class="form-group">
      <label for="price">価格</label>
      <%= f.text_field :price, class: "form-control price" %>
    </div>
    <div class="form-group">
      <label for="status">販売ステータス</label>
      <%= f.select :is_active, [['販売中', true], ['販売停止', false]] %>
    </div>
    <div class="form-group">
      <%= f.submit '作成', class: "btn btn-secondary" %>
    </div>
    <% end %>
  </div>
</div>
    

app/views/admin/items/index.html.erb
<h1 class="head-line title_h1 text-center">商品一覧</h1>
<div class="row">
  <div class="col-md-8 offset-md-1">
    <%= link_to new_admin_item_path, class: "btn btn-warning pull-right new_item" do %>
    <i class="fas fa-plus"></i>
    新規商品登録
    <% end %>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>商品画像</th>
          <th>商品名</th>
          <th>価格</th>
          <th>販売ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= image_tag item.image, height: "180" %></td>
          <td>
            <%= link_to admin_item_path(item), class: "btn-link" do %>
              <%= item.name %>
            <% end %>
          </td>
          <td><%= item.price %></td>
          <td>
            <% if item.is_active == true %>
              <p><i class="fas fa-bullseye red"></i>販売中</p>
            <% else %>
              <p><i class="fas fa-bullseye blue"></i>販売停止中</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2 class="head-line title_h2 text-center">商品新規登録</h2>
    <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="form-group">
      <label for="form-group">商品名</label>
      <%= f.text_field :name, class: "form-control name" %>
    </div>
    <div class="form-group">
      <label for="image">画像</label>
      <%= f.file_field :image, class: "form-control-image image" %>
    </div>
    <div class="form-group">
      <label for="introduction">商品説明</label>
      <%= f.text_area :introduction, class: "form-control introduction" %>
    </div>
    <div class="form-group">
      <label for="genre">ジャンル</label>
      <%= f.collection_select(:genre_id, @genres, :id, :name) %>
    </div>
    <div class="form-group">
      <label for="price">価格</label>
      <%= f.text_field :price, class: "form-control price" %>
    </div>
    <div class="form-group">
      <label for="status">販売ステータス</label>
      <%= f.select :is_active, [['販売中', true], ['販売停止', false]] %>
    </div>
    <div class="form-group">
      <%= f.submit '作成', class: "btn btn-secondary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<h1 class="head-line title_h1 text-center">商品詳細</h1>
<div class="row">
  <div class="col-md-8 offset-md-1">
    <table class="table">
      <tbody>
        <tr>
          <td><%= image_tag @item.image, height: "180" %></td>
          <td><%= @item.name %></td>
          <td><%= @item.price %>円</td>
          <td><%= @item.introduction %></td>
          <td>
            <% if @item.is_active == true %>
              <p><i class="fas fa-bullseye red"></i>販売中</p>
            <% else %>
              <p><i class="fas fa-bullseye blue"></i>販売停止中</p>
            <% end %>
          </td>
          <td><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-sm btn-success" %></td>
          <td><%= link_to "戻る", admin_items_path(@item), class: "btn btn-sm btn-success" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white">注文履歴詳細</h3>
    </div>
  </div>
  <div class="col-xs-7">
    <table class="table-borderless">
      <tr>
        <th>購入者</th>
        <td><%= @order.name %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td><%= @order.address %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
        <th>料金</th>
        <td><%= @order.total_payment %>円</td>
      </tr>
    </table>
  </div>
</div>