config/routes.rb
Rails.application.routes.draw do

  
  root to: "public/homes#top"
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    get 'homes/about'
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
  end
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
   namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    
    def address_display
        '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    has_one_attached :image
    belongs_to :customer
    belongs_to :item
    
    validates :amount, presence: true
    
    def sum_of_price
        item.with_tax_price * amount
    end
    
    def subtotal
        item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ordes, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, presence:true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana,presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_one_attached :image
    has_many :items, dependent: :destroy
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    has_many :order_details, dependent: :destroy
    has_many :cart_items, dependent: :destroy
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: {credit_card: 0, transfer: 1}
    enum status: {waiting: 0, confirm: 1, production: 2, preparing: 3, shipped: 4}
    has_one_attached :image
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: {impossible: 0, waiting: 1, production: 2, complete: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate!, except: [:top]

    def authenticate!
      if admin_signed_in?
        authenticate_admin!
      else
        authenticate_customer!
      end
    end
    
    def after_sign_in_path_for(resource)
        if customer_signed_in?
             customer_path(resource)
        else admin_sign_in?
          admin_root_path
        end
    end
    
    def after_sign_out_path_for(resource)
            root_path(resource)
    end
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
    
    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/1b2f943c3c.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Nagano cake</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_items_path, class: "btn btn-link" do %>
                <i class="fa-solid fa-shop" style="color: white;"></i>
                <span class="icon-name text-light">商品一覧</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_customers_path, class: "btn btn-link" do %>
                <i class="fa-regular fa-user" style="color: white;"></i>
                <span class="icon-name text-light">会員一覧</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_root_path, class: "btn btn-link" do %>
                <i class="fa-solid fa-arrow-down-wide-short" style="color: white;"></i>
                <span class="icon-name text-light">注文履歴一覧</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_genres_path, class: "btn btn-link" do %>
                <i class="fa-brands fa-elementor" style="color: white;"></i>
                <span class="icon-name text-light">ジャンル一覧</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: "btn btn-link" do %>
                <i class="fas fa-sign-out-alt" style="color: white;"></i>
                <span class="icon-nmae text-light">ログアウト</span>
                <% end %>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <% elsif customer_signed_in? %>
              <li class="nav-item">
                <%= link_to customer_path(current_customer), class: "btn btn-link" do %>
                <i class="fas fa-users" style="color: white;"></i>
                <span class="icon-name text-light">マイページ</span>
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: "btn btn-link" do %>
                <i class="fa-solid fa-shop" style="color: white;"></i>
                <span class="icon-name text-light">商品一覧</span>
                <% end %>
              </li>
              <li>
                <%= link_to cart_items_path, class: "btn btn-link" do %>
                <i class="fa-solid fa-cart-shopping" style="color: white;"></i>
                <span class="icon-name text-light">カート</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete, class: "btn btn-link" do %>
                <i class="fas fa-sign-out-alt" style="color: white;"></i>
                <span class="icon-name text-light">ログアウト</span>
                <% end %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to new_customer_registration_path, class: "btn btn-link" do %>
                <i class="fas fa-user-plus" style="color: white;"></i>
                <span class="icon-name text-light">新規登録</span>
              <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_customer_session_path, class: "btn btn-link" do %>
                <i class="fas fa-sign-in-alt" style="color: white;"></i>
                <span class="icon-name text-light">ログイン</span>
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>